### ISSUE TITLE
writer.quiz(); does not show anything 

### ISSUE THREAD

**Issue by Jfaler** [infinyte7/Anki-xiehanzi#1]
Thanks for making this awesome apkg. However, I can't get some cards to work on Windows 10 or my iPad when using an apple pencil or just mouse cursor. 
![doesnotwork](https://user-images.githubusercontent.com/8336385/76691320-f71e0c80-6606-11ea-8dc0-fb5507bbac4d.PNG)
This one works:
![working](https://user-images.githubusercontent.com/8336385/76691321-f8e7d000-6606-11ea-91a5-2711aa823a47.PNG)

**Comment by Jfaler** [comment]
To fix it I changed the width and height from 300 to 150

**Comment by infinyte7** [comment]
It may be due to slow internet. Let me check at my own devices.

**Comment by infinyte7** [comment]
I have just checked at my devices it working.

![check](https://user-images.githubusercontent.com/12841290/76693988-08145f80-6693-11ea-982b-ae8b6bbb1aed.png)

Can you elaborate more about the problem?
