### ISSUE TITLE
Proposals for interface: back navigate and restart buttons, green/red dot reposition

### ISSUE THREAD

**Issue by camerooncameroon** [infinyte7/Anki-xiehanzi#12]
Hello,
your addon is a masterpiece!
Thank you for your awesome job.

It's not an issue of course and not even so important, but just in case I'll put my proposals here:
1. Can two buttons be added to the existing: the back navigate button (to see the previous hanzi, the same as existing forward button, but in the opposite direction) and the reset quiz button (to practice again).
2. The green/red dot is very nice, but it takes a line of text which is sometimes essential on Android. Can this dot be repositioned, say, to lower left or any other corner of the stroke diagram, or to its central lower point? I want it to stay, it's very neat and even entertaining (who would expect it from a plain color dot yet?)) but also the overall layout to be more compact.

Thanks again!

**Comment by infinyte7** [comment]
Hi, 
In next update I will add the suggested ideas.

**Comment by camerooncameroon** [comment]
Thanks!
