### ISSUE TITLE
Additional Documentation for changing default settings

### ISSUE THREAD

**Issue by markmaterum** [infinyte7/Anki-xiehanzi#2]
When going through version 1.1 cards, the following settings are turned on by default: outline, simplified, pinyin, meaning; the following are turned off: traditional; additionally, the stroke and size sliders are set in the middle. Personally, I would prefer to have the outline, simplified, or traditional options set to off by default and be tested on my ability to produce the correct character or set of characters given Pinyin and translation. While I can turn off the outline and simplified options while reviewing the cards, changes do not place until the present card is answered and the the next card is shown, so the first card shown ends up giving me an unwanted hint. Could you please add additional documentation on what specifically to change in the code to change default settings for each option?

**Comment by infinyte7** [comment]
I have add this. 
https://github.com/infinyte7/Anki-xiehanzi/blob/master/Customize%20default%20setting.md

After AnkiDroid 2.10, changes will get reflect in current card.
Please update xiehanzi deck and AnkiDroid.
