### ISSUE TITLE
Hanzi Outline switcher does not work on desktop

### ISSUE THREAD

**Issue by camayl** [infinyte7/Anki-xiehanzi#3]
The switcher for the hanzi outline does not work on the PC. When toggling the switcher to "off", the outline stays visible, and the switcher is back to "on" on the next card.

I also tried it on another PC. Doesn't work.

On mobile it works fine.

Any way to fix this?

**Comment by infinyte7** [comment]
I have created a new deck when all switched off then it is working fine. But changes will get reflect from next card.

https://github.com/infinyte7/Anki-xiehanzi/blob/master/version%201.2/xiehanzi_all_off.apkg?raw=true 

Download this and import it to Anki then turn on the things, want to review/learn. Changes will get reflect from next card.

**Comment by infinyte7** [comment]
I tried to turn on but not working there may be some improvement to be done.

**Comment by infinyte7** [comment]
It will work on both AnkiDesktop and AnkiDroid. Download latest version.

**Comment by infinyte7** [comment]
Found the error.

```Persistence.setItem("key", true);```

It has some error when value is null.

```Persistence.setItem("key", "true");```

working fine.
