### ISSUE TITLE
Version 1.2 (desktop): changes are not reflected on same card

### ISSUE THREAD

**Issue by camayl** [infinyte7/Anki-xiehanzi#4]
As title says, changes are not shown on the same card, but on the next. 

On mobile it works fine.

**Comment by infinyte7** [comment]
For AnkiDriod I have create PR/Feature to reload current card. But for anki desktop I have no idea for reloading current card. I tried some like ```window.location.reload``` but that didn't work.

https://github.com/ankidroid/Anki-Android/pull/6134

**Comment by camayl** [comment]
Ok, it's not that important anyway, I just misunderstood the readme then (thought it applies to desktop and mobile).

**Comment by infinyte7** [comment]
Now it will work on both AnkiDesktop and AnkiDroid.

**Comment by infinyte7** [comment]
Found the error.

```Persistence.setItem("key", true);```

It has some error when value is null.

```Persistence.setItem("key", "true");```

working fine.
