### ISSUE TITLE
Kofi uses paypal, which is very annoying

### ISSUE THREAD

**Issue by mischa** [infinyte7/Anki-xiehanzi#5]
I keep trying to leave you a tip, but end up being blocked by the paypal UI (it keeps deleting everything I put in).

Can you add another way to leave tips? Like, put your wechat or something?

**Comment by infinyte7** [comment]
Well, After contacting Paypal. I came to know that they does not support the ko-fi, Patreon, Medium etc payment methods in India. So, you may try this http://paypal.com/infinyte7
Thanks for support

**Comment by infinyte7** [comment]
Thank you for support.
But I came to know that Paypal not support ko-fi and patreon.
