### ISSUE TITLE
Question concerning Version 2.0 of the Anki-xiehanzi deck (characters loading out of order w/o internet connection)

### ISSUE THREAD

**Issue by charliecjung** [infinyte7/Anki-xiehanzi#6]
I have been trying to test the Version 2.0 deck on AnkiDroid.

Loading the character data seems to be working fine.
However, sometimes the characters seem to load out of order.
(e.g. if we have <char 1><char 2><char 3>. Sometimes, char2 is loaded before char1 or char3 is loaded before char1.

I was wondering if this was a known issue.
I have tried looking at the actual JS code (await writeFunction(), loadScripts) but I can't seem to pinpoint why this behavior is happening.

**Comment by infinyte7** [comment]
I have tried that I also viewed the similar problems. So, I have implemented other way to do this. I put the HanziWriter data in separate field in Anki Decks. You can try this. Use [AnkiDroid parallel](https://github.com/ankidroid/Anki-Android/releases) build for testing. 

Extract HSK1 deck from zip file and try this. It is offline implementation. 
[HSK1.zip](https://github.com/infinyte7/Anki-xiehanzi/files/5786525/HSK1.zip)

**Comment by charliecjung** [comment]
Thank you for the prompt response!
I have tested it offline with an android device and it works well!
